main: pl.bartixen.bxcore.Main
version: 4.0.1
author: Bartixen
name: BxCore
api-version: 1.16
website: https://bartixen.pl
depend: [BxAuth]

commands:
  pomoc:
  pl:
  rtp:
  plugins:
  ver:
  lag:
  lagi:
  rtpnadaj:
  rtpusun:
  tps:
  server:
  serverstats:
  serwer:
  version:
  czat:
  blockworld:
  voucher:
  chat:
  cc:
  alert:
  list:
  lista:
  staty:
  statystyki:
  player:
  wl:
  bc:
  broadcast:
  gracz:
  ban:
  tempban:
  whitelist:
  tempmute:
  ip:
  graczip:
  banip:
  ipban:
  unban:
  kick:
  mute:
  unmute:
  clear:
  top:
  topki:
  bx:
  bxcore:
  day:
  enderchest:
  setspawn:
  v:
  vanish:
  ec:
  fly:
  socialspy:
  msg:
  r:
  ignore:
  dzien:
  noc:
  gm:
  gamemode:
  god:
  home:
  sethome:
  delhome:
  godmode:
  help:
  heal:
  helpop:
  invsee:
  swiat:
  oi:
  pogoda:
  night:
  repair:
  spawn:
  tp:
  teleport:
  tphere:
  s:
  tpa:
  tpaccept:
  tpdeny:
  weather:
  back:
  world:
  wb:
  speed:
  crafting: