#Plugin license key
key: o4398fJHBDsgjasdfbgLKHFASdfv9qa32bsd

#Server name | it will be displayed in many places
name: MC.SERWER.PL

#Taboo subtitles | REMEMBER TO MAKE THE NEXT LINE "\n"
#We accept:
# - "%name%" | Displays the server name
header: "&7\n&f&lWitaj na serwerze\n&7     &a&l%name%     &7\n&7"
footer: "&7\n&ffooter&f\n&7"

#Turns on the blood from the blows
blood: true

#AntyAfk
antyafk:
  #Should it be enabled?
  works: true
  #What should the delay be (in minutes)
  time: 5

#Chat format
#We accept:
# - "%nick%" | Displays the player's name
# - "%message%" | Displays the message
# - "%formatted%" | Displays the message with colors
# - "%team%" | Displays the player's team
chat:
  group-formats:
    gracz: '&c%team% &8[&f%nick%&8] &7-> &f%message%'
    admin: '&c%team% &8[&cADMIN&8] &8[&c%nick%&8] &7-> &c%formatted%'

#Motd displayed in the server list
motd:
  #First line of motd
  line-1: '&f&lMC.&9&lSERWER&f&l.PL &8» &fSerwer minecraft'
  #Second line of motd
  line-2: '&7'
  #This option always adds one to the maximum number of players | 23/24
  max-add-one: true
  #You set the maximum number of players | This will only work if you turn off (max-add-one)
  max: 1000

#You set spawn coordinates
spawn:
  #Coordinates (X)
  x: 0
  #Coordinates (Y)
  y: 100
  #Coordinates (Z)
  z: 0
  #Yaw | If you don't know what it is, set it to (90)
  yaw: 90
  #Pitch | If you don't know what it is, set it to (90)
  pitch: 90
  #World
  world: world

#If this is turned on, it will always be sunny in the world
weather: true

#This option sets its message in a brilliant comedy
unknowncommand: true

#Custom welcome messages
joinquitmessage: true

#Sending logs to the console from each command/event
logs: true

#When this is turned on, only one player needs to sleep for it to be daytime
oneplayersleep: true

#Shows notifications when a player digs up expensive items
antyxray: true

#You set anti-spam here
antyspam:
  #Should it be enabled?
  works: true
  #What should the delay be (in seconds)
  time: 3

#Additional option to dig out the spawner with a pickaxe with silk
silkspawners: true

#Blocks a given world
blockworld:
  #To the world world_nether
  nether:
    #Message when it starts
    message-date: 18-04-2021 18:00
    #Does this option work?
    blocked: true
  #To the world world_the_end
  end:
    #Message when it starts
    message-date: 19-04-2021 18:00
    #Does this option work?
    blocked: true

#Options END
end:
  #Tnt in end doesn't work
  blocked-tnt: true
  #No damage from entity
  blocked-damage-entity: true
  #You can't lay it down
  blocked-bed: true
  #Dragon Lvl
  dragon-lvl:
    #What is the current lvl
    lvl: 1
    #Is it working
    works: true
  #Does the dragoon fire elytra?
  dragon-elytra: true

#Weakening Mending
mending:
  #Is it working
  works: true
  #Weakening power (number 10 gives 70% worse mending)
  count: 10

#List of messages that are sent automatically
automessage:
  #Here you set whether messages should be sent
  works: true
  #Set the countdown time for sending the next message (in seconds)
  time: 5
  #You write a list of all messages
  tidings:
    - '&bWiadomosc pierwsza'
    - '&cWiadomosc druga'
    - '&aWiadomosc trzecia'

#List of commands blocked on the server
commandblock:
  - plugins
  - bukkit:pl
  - ?
  - bukkit:help
  - bukkit:plugins
  - bukkit:burn
  - bukkit:kill

#Home Settings
home:
  #How many free houses does the player have (vip permission bxcore.user.home)
  free: 1
  #How many houses are generally available (set to 0 if you want to exclude houses)
  everyone: 5

#Antilogout settings
antylogut:
  #How long should the antilogut last?
  time: 30