main: pl.bartixen.bxcore.Main
version: 6.2.7
author: Bartixen
name: BxCore
api-version: '1.20'
website: https://bartixen.pl
description: Core serwera
depend: [BxAuth]

commands:
  kit:
    description: Shows kit
  pvp:
    description: Enables/Disables pvp for the player
  pomoc:
    description: Displays all available commands for a given player
  pl:
    description: Shows information about the plugin
  logblock:
    description: Enables/Disables logblock
  rtp:
    description: Teleports the player to a random location on the map
  plugins:
    description: Shows information about the plugin
  ver:
    description: Shows information about the plugin
  lag:
    description: Displays important information about the server status
  lagi:
    description: Displays important information about the server status
  rtpnadaj:
    description: Provides the ability to teleport players to a given block
  rtpusun:
    description: Removes the ability to teleport players from a given block
  tps:
    description: Displays important information about the server status
  server:
    description: Displays important information about the server status
  serverstats:
    description: Displays important information about the server status
  serwer:
    description: Displays important information about the server status
  version:
    description: Shows information about the plugin
  czat:
    description: The command blocks/unblocks/clears the server chat
  blockworld:
    description: The command blocks/unlocks a given world
  voucher:
    description: Gives vouchers to the player's inventory
  wylaczenie:
    description: Within 60 seconds it turns off the server
  chat:
    description: The command blocks/unblocks/clears the server chat
  cc:
    description: The command clears the server chat
  alert:
    description: Sends the given alert to all players
  list:
    description: Shows a list of players and administrators
  lista:
    description: Shows a list of players and administrators
  staty:
    description: Shows player statistics
  statystyki:
    description: Shows player statistics
  player:
    description: Displays all relevant information about a given player
  wl:
    description: Manages the whitelist
  bc:
    description: Sends an alert to everyone in the chat
  broadcast:
    description: Sends an alert to everyone in the chat
  gracz:
    description: Displays all relevant information about a given player
  ban:
    description: Bans the player
  tempban:
    description: Temporarily bans the player
  whitelist:
    description: Manages the whitelist
  tempmute:
    description: Temporary mutes the player
  ip:
    description: Shows the IP of a given player
  anvil:
    description: He opens the anvil
  kowadlo:
    description: He opens the anvil
  graczip:
    description: Shows the IP of a given player
  banip:
    description: Blacklists a player/IP
  ipban:
    description: Blacklists a player/IP
  unban:
    description: Unbans the player
  kick:
    description: Kicks the player from the server
  mute:
    description: Mutes the player
  unmute:
    description: Mutates the player
  clear:
    description: Removes items from your inventory
  top:
    description: Shows player statistics
  topki:
    description: Shows player statistics
  bx:
    description: Shows information about the plugin
  bxcore:
    description: Shows information about the plugin
  day:
    description: Sets the day on the server
  enderchest:
    description: Opens the player's enderchest
  setspawn:
    description: Sets the spawn at the player's location
  v:
    description: Enables/Disables player vanish
  vanish:
    description: Enables/Disables player vanish
  ec:
    description: Opens the player's enderchest
  fly:
    description: Enables flying for a given player
  socialspy:
    description: Shows players' private messages
  msg:
    description: Sends a private message to a given player
  r:
    description: Replies to last private message
  ignore:
    description: Disables/Enables private messages from a given player
  dzien:
    description: Sets the day on the server
  noc:
    description: Sets night on the server
  gm:
    description: Sets a given game mode
  gamemode:
    description: Sets a given game mode
  god:
    description: Enables/Disables the player's immortality
  home:
    description: Opens the houses gui
  sethome:
    description: Opens the houses gui
  delhome:
    description: Opens the houses gui
  godmode:
    description: Enables/Disables the player's immortality
  help:
    description: Displays all available commands for a given player
  heal:
    description: Heals the player
  helpop:
    description: Sends a message to the administration
  invsee:
    description: Opens the player's inventory
  swiat:
    description: Teleports the player to a given world
  oi:
    description: Opens the player's inventory
  pogoda:
    description: Sets a given weather on the server
  night:
    description: Sets night on the server
  repair:
    description: Repairs items
  spawn:
    description: Teleports to spawn
  tp:
    description: Teleports to a given player or cord
  teleport:
    description: Teleports to a given player or cord
  tphere:
    description: Teleports a given player to the person who used the command
  s:
    description: Teleports a given player to the person who used the command
  tpa:
    description: Sends a teleporation request to a given player
  tpaccept:
    description: Accepts teleportations from a given player
  tpdeny:
    description: Removes a teleport request from a given player
  weather:
    description: Sets a given weather on the server
  back:
    description: Teleports to the last saved location of a given player
  world:
    description: Teleports the player to a given world
  wb:
    description: Opens crafting for the player
  speed:
    description: Sets a given walking/flying speed for the player
  crafting:
    description: Opens crafting for the player
  permission:
    description: Displays permission commands
  pex:
    description: Displays permission commands
  perm:
    description: Displays permission commands
  nagrody:
    description: Opens the rewards gui
  nagroda:
    description: Opens the rewards gui
  reward:
    description: Opens the rewards gui